import java.io.IOException;
import java.sql.* ;
import java.util.List;
import java.util.ArrayList;
import java.util.Date;
import java.util.Map;
import java.util.LinkedHashMap;
import java.lang.*;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.servlet.Servlet;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.sql.DataSource;

import org.commonmark.node.*;
import org.commonmark.parser.Parser;
import org.commonmark.renderer.html.HtmlRenderer;

/**
 * Servlet implementation class for Servlet: ConfigurationTest
 *
 */
public class Editor extends HttpServlet {
    public Editor() {}

    public void init() throws ServletException
    {
        /*  write any servlet initialization code here or remove this function */
    }
    
    public void destroy()
    {
        /*  write any servlet cleanup code here or remove this function */
    }

    /**
     * Handles HTTP GET requests
     * 
     */
    public void doGet(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException 
    {
	// implement your GET method handling code here
	// currently we simply show the page generated by "edit.jsp"
        request.getRequestDispatcher("/edit.jsp").forward(request, response);
    }
    
    public static Map<String, String> splitQuery(String queryString)
    {
        Map<String, String> queryPairs = new LinkedHashMap<String, String>();
        String[] pairs = queryString.split("&");
        for(String pair : pairs)
        {
            int index = pair.indexOf("=");
            queryPairs.put(pair.substring(0, index), pair.substring(index+1));
        }
        return queryPairs;
    }
    /**
     * Handles HTTP POST requests
     * 
     */
    public void doPost(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException 
    {
	// Parse query string
        String queryString = request.getQueryString();

        if(queryString == null)
        {
            System.out.println("No query string found");
            return;
        }

        Map<String, String> queryPairs = splitQuery(queryString);
        String action = queryPairs.get("action");

        switch(action)
        {
            case "open":
            {
                String username = queryPairs.get("username");
                int postId = Integer.parseInt(queryPairs.get("postid"));
                break;
            }      
            case "save":
            {
                System.out.println("Save detected");
                break;
            }
            case "delete":
            {
                System.out.println("Delete");
                break;
            }
            case "preview":
            {
                System.out.println("Preview");
                break;
            }
            case "list":
            {
                System.out.println("List");
                break;
            }
            default:
            {
                System.out.println("Action not recognized");
                return;
            }
        }

	// Render "edit.jsp"
        request.getRequestDispatcher("/edit.jsp").forward(request, response);
    }
}

